export const ErrorCodes = {
  // Auth
  AUTH_UNAUTHENTICATED: 'AUTH.UNAUTHENTICATED',
  AUTH_UNAUTHORIZED: 'AUTH.UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
  AUTH_BANNED: 'AUTH.BANNED',
  AUTH_INACTIVE: 'AUTH.INACTIVE',
  AUTH_RATE_LIMITED: 'AUTH.RATE_LIMITED',
  AUTH_MUST_CHANGE_PASSWORD: 'AUTH.MUST_CHANGE_PASSWORD',
  AUTH_REGISTRATION_DISABLED: 'AUTH.REGISTRATION_DISABLED',

  // Validation / Request
  BAD_REQUEST: 'REQUEST.BAD_REQUEST',
  VALIDATION_ERROR: 'REQUEST.VALIDATION_ERROR',
  NOT_FOUND: 'RESOURCE.NOT_FOUND',
  CONFLICT: 'RESOURCE.CONFLICT',
  RATE_LIMIT_EXCEEDED: 'REQUEST.RATE_LIMIT_EXCEEDED',

  // Modules
  CLASS_NOT_FOUND: 'CLASS.NOT_FOUND',
  LESSON_NOT_FOUND: 'LESSON.NOT_FOUND',
  EXERCISE_NOT_FOUND: 'EXERCISE.NOT_FOUND',
  SESSION_NOT_FOUND: 'SESSION.NOT_FOUND',
  SESSION_CLOSED: 'SESSION.CLOSED',
  PIN_INVALID: 'SESSION.PIN_INVALID',
  WALL_LOCKED: 'WALL.LOCKED',
  WALL_MODERATED: 'WALL.MODERATED',

  // AI
  AI_PROVIDER_ERROR: 'AI.PROVIDER_ERROR',
  AI_QUOTA_EXCEEDED: 'AI.QUOTA_EXCEEDED',
  AI_RATE_LIMITED: 'AI.RATE_LIMITED',
  AI_TIMEOUT: 'AI.TIMEOUT',
  AI_NO_KEY: 'AI.NO_KEY',
  AI_SSRF_BLOCKED: 'AI.SSRF_BLOCKED',

  // Server
  INTERNAL_ERROR: 'SERVER.INTERNAL_ERROR',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]
